In [1]:
# Support Vector Machine (SVM)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [12]:
# Importing the dataset
dataset = pd.read_csv("https://raw.githubusercontent.com/gnaneshwari1802/29th/master/Social_Network_Ads.csv?token=GHSAT0AAAAAACGCKUCFKNMX4MDUUKBSBU46ZIK6TZA")
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values
dataset,X,y


(      User ID  Gender  Age  EstimatedSalary  Purchased
 0    15624510    Male   19            19000          0
 1    15810944    Male   35            20000          0
 2    15668575  Female   26            43000          0
 3    15603246  Female   27            57000          0
 4    15804002    Male   19            76000          0
 ..        ...     ...  ...              ...        ...
 395  15691863  Female   46            41000          1
 396  15706071    Male   51            23000          1
 397  15654296  Female   50            20000          1
 398  15755018    Male   36            33000          0
 399  15594041  Female   49            36000          1
 
 [400 rows x 5 columns],
 array([[    19,  19000],
        [    35,  20000],
        [    26,  43000],
        [    27,  57000],
        [    19,  76000],
        [    27,  58000],
        [    27,  84000],
        [    32, 150000],
        [    25,  33000],
        [    35,  65000],
        [    26,  80000],
        [    26

In [13]:
dataset.describe

<bound method NDFrame.describe of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [14]:
dataset.info

<bound method DataFrame.info of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [15]:
dataset.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [17]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
X_train, X_test, y_train, y_test


(array([[ 1.94321462,  2.18056084],
        [ 2.03872775,  0.38930459],
        [-1.30423178, -0.4329114 ],
        [-1.11320552, -1.02020853],
        [ 1.94321462, -0.93211396],
        [ 0.41500455,  0.30121002],
        [ 0.22397829,  0.15438573],
        [ 2.03872775,  1.76945285],
        [ 0.79705706, -0.84401939],
        [ 0.31949142, -0.28608712],
        [ 0.41500455, -0.16862769],
        [-0.0625611 ,  2.23929055],
        [-1.39974491, -0.63846539],
        [-1.20871865, -1.07893824],
        [-1.30423178,  0.41866944],
        [-1.01769239,  0.77104772],
        [-1.39974491, -0.19799255],
        [ 0.98808332, -1.07893824],
        [ 0.98808332,  0.59485858],
        [ 0.41500455,  1.00596657],
        [ 0.60603081, -0.9027491 ],
        [-0.54012675,  1.47580428],
        [ 0.03295203, -0.57973568],
        [-0.54012675,  1.91627713],
        [ 1.37013584, -1.43131652],
        [ 1.46564897,  1.00596657],
        [ 0.12846516, -0.81465453],
        [ 0.03295203, -0.256

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Training the Kernel SVM model on the Training set


In [20]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

Predicting the Test set results

In [21]:
y_pred = classifier.predict(X_test)

Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55  3]
 [ 1 21]]


Applying k-Fold Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))


Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, np.arange(start = X_set[:, 1].min() - 1,
                                                                                        stop = X_set[:, plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T). alpha = 0.75, cmap = ListedColormap(('yellow', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)): plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
c = ListedColormap(('red', 'blue'))(i), label = j) plt.title('Kernel SVM (Training set)')
plt.xlabel('Age') plt.ylabel('Estimated Salary') plt.legend()
plt.show()